### ISSUE TITLE
mergeless-persistent fails to build on ghc-9.4.3 Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [NorfairKing/mergeless#3]
```
Building library for mergeless-persistent-0.1.0.0..                                                                     [431/196911]
[1 of 2] Compiling Data.Mergeless.Persistent                                                                                        
                                                                                                                                    
/var/stackage/work/unpack-dir/unpacked/mergeless-persistent-0.1.0.0-f2e294d6941e232e507677de74afc239b233a7f47c4fbff361c11a05fc9fa200
/src/Data/Mergeless/Persistent.hs:117:7: error:                                                                                         • Could not deduce (SafeToInsert clientRecord)                                                                                          arising from a use of ‘insert_’                                                                                             
      from the context: (PersistEntity clientRecord, PersistField sid,                                                              
                         PersistEntityBackend clientRecord ~ SqlBackend, MonadIO m)                                                 
        bound by the type signature for:                                                                                            
                   clientSyncProcessor :: forall clientRecord sid (m :: * -> *) a.                                                  
                                          (PersistEntity clientRecord, PersistField sid,                                            
                                           PersistEntityBackend clientRecord ~ SqlBackend,                                          
                                           MonadIO m) =>                                                                            
                                          (sid -> a -> clientRecord)                                                                                                          -> EntityField clientRecord (Maybe sid)                                                   
                                          -> EntityField clientRecord Bool                      
                                          -> ClientSyncProcessor                                                                    
                                               (Key clientRecord) sid a (SqlPersistT m)                                             
        at src/Data/Mergeless/Persistent.hs:(101,1)-(113,62)                                                                        
      Possible fix:                                                                                                                 
        add (SafeToInsert clientRecord) to the context of                                                                           
          the type signature for:                                                                                                   
            clientSyncProcessor :: forall clientRecord sid (m :: * -> *) a.                                                         
                                   (PersistEntity clientRecord, PersistField sid,                                                   
                                    PersistEntityBackend clientRecord ~ SqlBackend, MonadIO m) =>                                   
                                   (sid -> a -> clientRecord)                                                                                                          -> EntityField clientRecord (Maybe sid)                                                          
                                   -> EntityField clientRecord Bool                                                                 
                                   -> ClientSyncProcessor (Key clientRecord) sid a (SqlPersistT m)                                  
    • In the first argument of ‘($)’, namely ‘insert_’                                                                              
      In the expression: insert_ $ func si st                                                                                       
      In the second argument of ‘($)’, namely                     
        ‘\ (si, st) -> insert_ $ func si st’
    |
117 |       insert_ $ func si st
    |       ^^^^^^^

/var/stackage/work/unpack-dir/unpacked/mergeless-persistent-0.1.0.0-f2e294d6941e232e507677de74afc239b233a7f47c4fbff361c11a05fc9fa200
/src/Data/Mergeless/Persistent.hs:162:42: error:
    • Could not deduce (SafeToInsert record)
        arising from a use of ‘insert’
      from the context: (PersistEntity record,                                                                          [389/196911]
                         PersistEntityBackend record ~ SqlBackend, MonadIO m)
        bound by the type signature for:
                   serverSyncProcessor :: forall record (m :: * -> *) a ci.
                                          (PersistEntity record,
                                           PersistEntityBackend record ~ SqlBackend, MonadIO m) =>
                                          [Filter record]
                                          -> (record -> a)
                                          -> (a -> record)
                                          -> ServerSyncProcessor ci (Key record) a (SqlPersistT m)
        at src/Data/Mergeless/Persistent.hs:(144,1)-(157,55)
      Possible fix:
        add (SafeToInsert record) to the context of
          the type signature for: 
            serverSyncProcessor :: forall record (m :: * -> *) a ci.
                                   (PersistEntity record, PersistEntityBackend record ~ SqlBackend,
                                    MonadIO m) =>
                                   [Filter record]
                                   -> (record -> a)
                                   -> (a -> record)
                                   -> ServerSyncProcessor ci (Key record) a (SqlPersistT m)
    • In the first argument of ‘(.)’, namely ‘insert’
      In the second argument of ‘($)’, namely ‘insert . funcFrom’
      In the expression: mapM $ insert . funcFrom
    |
162 |     serverSyncProcessorAddItems = mapM $ insert . funcFrom
    |                                          ^^^^^^

/var/stackage/work/unpack-dir/unpacked/mergeless-persistent-0.1.0.0-f2e294d6941e232e507677de74afc239b233a7f47c4fbff361c11a05fc9fa200
/src/Data/Mergeless/Persistent.hs:219:7: error:
    • Could not deduce (SafeToInsert record)
        arising from a use of ‘insert_’
      from the context: (Ord sid, PersistEntity record, PersistField sid,
                         PersistEntityBackend record ~ SqlBackend, MonadIO m)
        bound by the type signature for:
                   serverSyncProcessorWithCustomId :: forall sid record (m :: * -> *)
                                                             a ci. 
                                                      (Ord sid, PersistEntity record,
                                                       PersistField sid,
                                                       PersistEntityBackend record ~ SqlBackend,
                                                       MonadIO m) =>
                                                      SqlPersistT m sid
                                                      -> EntityField record sid                                         [347/196911]
                                                      -> [Filter record]
                                                      -> (record -> (sid, a))
                                                      -> (sid -> a -> record)
                                                      -> ServerSyncProcessor
                                                           ci sid a (SqlPersistT m)
        at src/Data/Mergeless/Persistent.hs:(192,1)-(211,46)
      Possible fix:
        add (SafeToInsert record) to the context of
          the type signature for: 
            serverSyncProcessorWithCustomId :: forall sid record (m :: * -> *)
                                                      a ci.
                                               (Ord sid, PersistEntity record, PersistField sid,
                                                PersistEntityBackend record ~ SqlBackend,
                                                MonadIO m) =>
                                               SqlPersistT m sid
                                               -> EntityField record sid
                                               -> [Filter record]
                                               -> (record -> (sid, a))
                                               -> (sid -> a -> record)
                                               -> ServerSyncProcessor ci sid a (SqlPersistT m)
    • In a stmt of a 'do' block: insert_ record
      In the expression:
        do sid <- genId
           let record = funcFrom sid a
           insert_ record
           pure sid
      In the second argument of ‘($)’, namely
        ‘\ a
           -> do sid <- genId
                 let ...
                 ....’
    |
219 |       insert_ record
    |       ^^^^^^^

/var/stackage/work/unpack-dir/unpacked/mergeless-persistent-0.1.0.0-f2e294d6941e232e507677de74afc239b233a7f47c4fbff361c11a05fc9fa200
/src/Data/Mergeless/Persistent.hs:237:40: error:
    • Could not deduce (SafeToInsert clientRecord)
        arising from a use of ‘insert’
      from the context: (PersistEntity clientRecord,
                         PersistEntityBackend clientRecord ~ SqlBackend, MonadIO m)
        bound by the type signature for:                                                                                [305/196911]
                   setupUnsyncedClientQuery :: forall clientRecord (m :: * -> *) a.
                                               (PersistEntity clientRecord,
                                                PersistEntityBackend clientRecord ~ SqlBackend,
                                                MonadIO m) =>
                                               (a -> clientRecord) -> [a] -> SqlPersistT m ()
        at src/Data/Mergeless/Persistent.hs:(228,1)-(236,18)
      Possible fix:
        add (SafeToInsert clientRecord) to the context of
          the type signature for: 
            setupUnsyncedClientQuery :: forall clientRecord (m :: * -> *) a.
                                        (PersistEntity clientRecord,
                                         PersistEntityBackend clientRecord ~ SqlBackend,
                                         MonadIO m) =>
                                        (a -> clientRecord) -> [a] -> SqlPersistT m ()
    • In the first argument of ‘(.)’, namely ‘insert’
      In the first argument of ‘mapM_’, namely ‘(insert . func)’
      In the expression: mapM_ (insert . func)
    |
237 | setupUnsyncedClientQuery func = mapM_ (insert . func)
    |                                        ^^^^^^

/var/stackage/work/unpack-dir/unpacked/mergeless-persistent-0.1.0.0-f2e294d6941e232e507677de74afc239b233a7f47c4fbff361c11a05fc9fa200
/src/Data/Mergeless/Persistent.hs:261:5: error:
    • Could not deduce (SafeToInsert clientRecord)
        arising from a use of ‘insert_’
      from the context: (PersistEntity clientRecord,
                         PersistEntityBackend clientRecord ~ SqlBackend, MonadIO m)
        bound by the type signature for:
                   setupClientQuery :: forall clientRecord (m :: * -> *) a sid.
                                       (PersistEntity clientRecord,
                                        PersistEntityBackend clientRecord ~ SqlBackend,
                                        MonadIO m) =>
                                       (a -> clientRecord)
                                       -> (sid -> a -> clientRecord)
                                       -> (sid -> clientRecord)
                                       -> ClientStore (Key clientRecord) sid a
                                       -> SqlPersistT m ()
        at src/Data/Mergeless/Persistent.hs:(242,1)-(254,18)
      Possible fix:
        add (SafeToInsert clientRecord) to the context of
          the type signature for: 
            setupClientQuery :: forall clientRecord (m :: * -> *) a sid.                                                [263/196911]
                                (PersistEntity clientRecord,
                                 PersistEntityBackend clientRecord ~ SqlBackend, MonadIO m) =>
                                (a -> clientRecord)
                                -> (sid -> a -> clientRecord)
                                -> (sid -> clientRecord)
                                -> ClientStore (Key clientRecord) sid a
                                -> SqlPersistT m ()
    • In the expression: insert_ (funcS sid st)
      In the second argument of ‘($)’, namely
        ‘\ (sid, st) -> insert_ (funcS sid st)’
      In a stmt of a 'do' block:
        forM_ (M.toList clientStoreSynced)
          $ \ (sid, st) -> insert_ (funcS sid st)
    |
261 |     insert_ (funcS sid st)
    |     ^^^^^^^
```
